IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[bc_extract_retail_strategy]') AND type in (N'U'))
DROP TABLE [bc_extract_retail_strategy]
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[bc_extract_retail_strategy]') AND type in (N'U'))
BEGIN
CREATE TABLE [bc_extract_retail_strategy](
	[mg_name] [nvarchar](50) NOT NULL,
	[mg_retail_item_type_code] [nvarchar](1) NOT NULL,
	[mg_standard_flag] [nvarchar](1) NOT NULL,
	[mgm_name] [nvarchar](50) NOT NULL,
	[ml_name] [nvarchar](50) NOT NULL,
	[ml_default_ranking] [int] NOT NULL,
	[ml_high_margin] [smallmoney] NOT NULL,
	[ml_low_margin] [smallmoney] NOT NULL,
	[ml_target_margin] [smallmoney] NOT NULL,
	[orig_merch_group_id] [int] NULL,
	[orig_merch_group_member_id] [int] NULL,
	[orig_merch_level_id] [int] NULL,
	[resolved_merch_group_id] [int] NULL,
	[resolved_merch_group_member_id] [int] NULL,
	[resolved_merch_level_id] [int] NULL
) ON [PRIMARY]
END

IF OBJECT_ID('bc_extract_retail_strategy_worktable') IS NOT NULL
  DROP TABLE bc_extract_retail_strategy_worktable
GO

CREATE TABLE bc_extract_retail_strategy_worktable
(mg_name NVARCHAR(50) NOT NULL,
 mgm_name NVARCHAR(50) NOT NULL,
 ml_name NVARCHAR(50) NOT NULL,
 default_ranking INT NULL default 999,
 ml_high_margin smallmoney NULL DEFAULT .5,
 ml_low_margin smallmoney NULL DEFAULT .1,
 ml_target_margin smallmoney NULL DEFAULT .25)
GO

/* Paste the INSERT statements from the spreadsheet here */
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Alcohol','Beer','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Alcohol','Liquor','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Alcohol','Miscellaneous','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Alcohol','Mixers','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Alcohol','Wine','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'CVO','601 CVO Dairy','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'CVO','601 CVO Dairy','yFranchise'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'CVO','601 CVO Non Dairy','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'CVO','601 CVO Non Dairy','yFranchise'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'CVO','601 CVO Non Dairy','yPhiladelphia'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'CVO','601 CVO Non Dairy','zStandard East'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'CVO','601 CVO Non Dairy','zStandard West'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'CVO','601 CVO Non Dairy','zzzMN'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'CVO','901 CVO','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'CVO','901 CVO','yFranchise'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'CVO','901 CVO','yG and J Pepsi'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'CVO','901 CVO','yPhiladelphia'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'CVO','901 CVO','zConsolidated'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'CVO','901 CVO','zNon Consolidated'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'CVO','901 CVO','zzMN'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Default Strategy','Default Group','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Bakery','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Bakery','zFranchise'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Deli Case','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Deli Case','yCompany 1'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Deli Case','yNeptune'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Deli Case','zAtlantic'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Deli Case','zFranchise'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Deli Case','zMidwest'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','yColony'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','yDisney'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','yPhilly Tax'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','ySouth Carolina'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zFL Ft Myers Naples'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zFL Jacksonville'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zFL Miami Ft Lauderdale'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zFL Orlando Daytona Beach Melbourn'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zFL Tampa St Petersburg'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zFL West Palm Beach Ft Pierce'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zGA Atlanta'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zGA Savannah'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zIL Chicago'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zIN Ft Wayne'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zIN Indianapolis'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zIN Lafayette'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zIN South Bend'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zIN Terre Haute'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zKY Bowling Green'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zKY Lexington'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zKY Louisville'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zMA NH Boston Manchester'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zMA RI Providence New Bedford'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zMA Springfield Holyoke'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zMD Washington DC Hagerstown'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zMI Detroit'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zMI Flint Saginaw Bay City'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zMI Grand Rapids Kala Battle Creek'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zMI Lansing'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zMI Traverse City Cadillac'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zNC Charlotte'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zNC Greenville New Bern Washington'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zNC Raleigh Durham Fayetteville'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zNC VA Greensboro High Point Winston'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zNC VA Norfolk Portsmouth Newport New'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zNC Wilmington'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zNY Albany Schenectady Troy'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zNY Binghamton'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zNY Buffalo'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zNY Elmira'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zNY New York'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zNY Rochester'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zNY Syracuse'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zNY Utica'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zNY Watertown'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zOH Cincinnati'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zOH Cleveland'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zOH Columbus'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zOH Dayton'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zOH Lima'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zOH Toledo'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zOH WV Wheeling Steubenville'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zOH Youngstown'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zOH Zanesville'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zPA Harrisburg Lancaster Lebanon'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zPA Philadelphia'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zPA Pittsburgh'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zPA Wilkes Barre Scranton'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zSC Charleston'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zSC Columbia'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zSC Florence Myrtle Beach'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zSC Greenville Spartanburg'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zTN Chattanooga'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zTN Jackson'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zTN Knoxville'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zTN Nashville'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zTX Houston'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zVA Charlottesville'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zVA Harrisonburg'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zVA Richmond Petersburg'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zVA Roanoke Lynchburg'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zWI Green Bay'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zWI Madison'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zWI Milwaukee'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zWV Bluefield Beckley Oak Hill'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zWV Charleston Huntington'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zWV Clarksburg Weston'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dispensed Beverages','zWV Parkersburg'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Dunkin','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Fruit','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Ice','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Ice','zArctic Company 1'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Ice','zArctic Holiday Copacker'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Ice','zArctic Legacy'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Ice','zArctic Long Island Copacker'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Ice','zArctic Reddy Copacker'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Ice','zCorbin Ice'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Ice','zFranchise'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Ice','zHome City East'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Ice','zSomerset Ice'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Other Franchise','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Prepared Foods','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Prepared Foods','zCompany 1'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Food Service and Technology','Prepared Foods','zFranchise'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','Auto','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','Auto','zCompany1'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','Auto','zFranchise '
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','Bags/Stickers','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','Bait','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','Bait','zFranchise'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','Confections','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','Confections','zCompany1'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','Confections','zFranchise '
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','Cookie/Cracker','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','Cookie/Cracker','zCompany1'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','Cookie/Cracker','zFranchise'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','DSD Cookie/Cracker/Pastry','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','DSD Cookie/Cracker/Pastry','zFranchise '
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','DSD Salty/Meat Snacks','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','DSD Salty/Meat Snacks','zFranchise '
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','Flowers','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','Flowers','zFranchise'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','Grocery','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','Grocery','zCompany1'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','Grocery','zFranchise '
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','HBA','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','HBA','zCompany1'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','HBA','zFranchise'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','Meat Snacks','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','Meat Snacks','zFranchise'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','Newspapers','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','Newspapers','zFranchise'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','Non-Food','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','Non-Food','zCompany1'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','Non-Food','zFranchise '
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','Novelty','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','Novelty','zFranchise '
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','Outside','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','Outside','zFranchise'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','Pastry','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','Pastry','zCompany1'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','Pastry','zFranchise '
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','Salty','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','Salty','zCompany1'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'General Merchandise','Salty','zFranchise '
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Miscellaneous Sales','Charity','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Miscellaneous Sales','Services','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','vMa orleans high cigar'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','wMa peabody high cigar'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','xChicago'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','xMa filtered cigar'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','xMn zone 1 minneapolis'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','xMn zone 2 bloomington'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','xMn zone 2 brooklyn'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','xMn zone 2 maplewood'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','xMn zone 2 minneapolis'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','xMn zone 2 ritchfield'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','xMn zone 2 st paul'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','xMn zone 4 maplewood'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','xMn zone 5 st paul'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','xMn zone 6 st paul'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','xNew york city'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','xPhiladelphia (East)'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','xPhiladelphia (West)'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','yBronx county'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','yCook'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','yCuyahoga'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','yKings county'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','yMa filtered cigar'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','yMa orleans high cigar'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','yMa peabody high cigar'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','yMassachusetts high cigar'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','yMinnesota zone 01'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','yMinnesota zone 02'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','yMinnesota zone 03'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','yMinnesota zone 04'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','yMinnesota zone 05'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','yMinnesota zone 06'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','yMinnesota zone 07 st min'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','yMn zone 2 pierz'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','yNew york county'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','yPhiladelphia county (East)'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','yPhiladelphia county (West)'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','yQueens county'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','yRichmond county'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','ySouth dakota zone 01'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','yVa - 1.20'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','yVa - 1.50'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','yVa - 11.50'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','yVa - 2.00'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','yVa - 2.50'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','yVa - 3.00'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','yVa - 3.50'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','yVa - 4.00'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','yVa - 4.50'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','yVa - 5.00'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','yVa - 5.40'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','yVa - 7.50'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','yVa - 8.50'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','yVa - 9.00'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','yWisconsin zone 01'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','zAlabama'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','zConnecticut'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','zDelaware'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','zFlorida'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','zFranchise MN TOB'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','zGeorgia'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','zIllinois'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','zIndiana'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','zKentucky'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','zMassachusetts'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','zMichigan'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','zMinnesota'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','zNew hampshire'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','zNew jersey'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','zNew york'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','zNorth carolina'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','zOhio'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','zPennsylvania (East)'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','zPennsylvania (West)'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','zRhode island'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','zSouth carolina'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','zSouth dakota'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','zTennessee'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','zTexas'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','zVirginia'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','zWest virginia'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Cigars','zWisconsin'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','xChicago'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','xMn zone 1 minneapolis'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','xMn zone 2 bloomington'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','xMn zone 2 brooklyn'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','xMn zone 2 maplewood'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','xMn zone 2 minneapolis'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','xMn zone 2 ritchfield'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','xMn zone 2 st paul'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','xMn zone 4 maplewood'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','xMn zone 5 st paul'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','xMn zone 6 st paul'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','xNew york city'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','xPhiladelphia (East)'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','xPhiladelphia (West)'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','yBronx county'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','yCook'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','yCuyahoga'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','yKings county'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','yMinnesota zone 01'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','yMinnesota zone 02'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','yMinnesota zone 03'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','yMinnesota zone 04'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','yMinnesota zone 05'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','yMinnesota zone 06'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','yMinnesota zone 07 st min'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','yMn zone 2 pierz'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','yNew york county'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','yPhiladelphia county (East)'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','yPhiladelphia county (West)'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','yQueens county'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','yRichmond county'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','ySouth dakota zone 01'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','yVa - 1.20'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','yVa - 1.50'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','yVa - 11.50'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','yVa - 2.00'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','yVa - 2.50'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','yVa - 3.00'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','yVa - 3.50'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','yVa - 4.00'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','yVa - 4.50'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','yVa - 5.00'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','yVa - 5.40'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','yVa - 7.50'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','yVa - 8.50'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','yVa - 9.00'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','yWisconsin zone 01'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','zAlabama'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','zConnecticut'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','zDelaware'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','zFlorida'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','zFranchise MN'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','zGeorgia'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','zIllinois'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','zIndiana'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','zKentucky'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','zMassachusetts'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','zMichigan'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','zMinnesota'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','zNew hampshire'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','zNew jersey'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','zNew york'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','zNorth carolina'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','zOhio'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','zPennsylvania (East)'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','zPennsylvania (West)'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','zRhode island'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','zSouth carolina'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','zSouth dakota'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','zTennessee'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','zTexas'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','zVirginia'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','zWest virginia'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB E-Cigs','zWisconsin'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','vMa orleans high cigar'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','wMa peabody high cigar'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','xChicago'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','xMa filtered cigar'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','xMn zone 1 minneapolis'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','xMn zone 2 bloomington'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','xMn zone 2 brooklyn'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','xMn zone 2 maplewood'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','xMn zone 2 minneapolis'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','xMn zone 2 ritchfield'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','xMn zone 2 st paul'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','xMn zone 4 maplewood'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','xMn zone 5 st paul'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','xMn zone 6 st paul'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','xNew york city'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','xPhiladelphia (East)'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','xPhiladelphia (West)'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','yBronx county'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','yCook'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','yCuyahoga'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','yKings county'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','yMa filtered cigar'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','yMa orleans high cigar'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','yMa peabody high cigar'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','yMassachusetts high cigar'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','yMinnesota zone 01'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','yMinnesota zone 02'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','yMinnesota zone 03'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','yMinnesota zone 04'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','yMinnesota zone 05'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','yMinnesota zone 06'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','yMinnesota zone 07 st min'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','yMn zone 2 pierz'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','yNew york county'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','yPhiladelphia county (East)'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','yPhiladelphia county (West)'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','yQueens county'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','yRichmond county'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','ySouth dakota zone 01'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','yVa - 1.20'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','yVa - 1.50'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','yVa - 11.50'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','yVa - 2.00'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','yVa - 2.50'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','yVa - 3.00'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','yVa - 3.50'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','yVa - 4.00'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','yVa - 4.50'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','yVa - 5.00'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','yVa - 5.40'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','yVa - 7.50'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','yVa - 8.50'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','yVa - 9.00'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','yWisconsin zone 01'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','zAlabama'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','zConnecticut'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','zDelaware'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','zFlorida'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','zFranchise Vets MN'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','zFranchise Vets SD'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','zFranchise Vets WI'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','zGeorgia'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','zIllinois'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','zIndiana'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','zKentucky'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','zMassachusetts'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','zMichigan'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','zMinnesota'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','zNew hampshire'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','zNew jersey'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','zNew york'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','zNorth carolina'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','zOhio'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','zPennsylvania (East)'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','zPennsylvania (West)'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','zRhode island'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','zSouth carolina'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','zSouth dakota'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','zTennessee'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','zTexas'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','zVirginia'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','zWest virginia'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Moist','zWisconsin'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','Default'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','xChicago'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','xMn zone 1 minneapolis'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','xMn zone 2 bloomington'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','xMn zone 2 brooklyn'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','xMn zone 2 maplewood'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','xMn zone 2 minneapolis'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','xMn zone 2 ritchfield'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','xMn zone 2 st paul'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','xMn zone 4 maplewood'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','xMn zone 5 st paul'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','xMn zone 6 st paul'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','xNew york city'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','xPhiladelphia (East)'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','xPhiladelphia (West)'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','yBronx county'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','yCook'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','yCuyahoga'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','yKings county'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','yMinnesota zone 01'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','yMinnesota zone 02'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','yMinnesota zone 03'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','yMinnesota zone 04'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','yMinnesota zone 05'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','yMinnesota zone 06'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','yMinnesota zone 07 st min'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','yMn zone 2 pierz'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','yNew york county'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','yPhiladelphia county (East)'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','yPhiladelphia county (West)'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','yQueens county'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','yRichmond county'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','ySouth dakota zone 01'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','yVa - 1.20'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','yVa - 1.50'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','yVa - 11.50'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','yVa - 2.00'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','yVa - 2.50'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','yVa - 3.00'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','yVa - 3.50'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','yVa - 4.00'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','yVa - 4.50'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','yVa - 5.00'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','yVa - 5.40'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','yVa - 7.50'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','yVa - 8.50'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','yVa - 9.00'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','yWisconsin zone 01'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','zAlabama'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','zConnecticut'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','zDelaware'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','zFlorida'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','zGeorgia'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','zIllinois'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','zIndiana'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','zKentucky'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','zMassachusetts'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','zMichigan'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','zMinnesota'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','zNew hampshire'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','zNew jersey'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','zNew york'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','zNorth carolina'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','zOhio'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','zPennsylvania (East)'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','zPennsylvania (West)'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','zRhode island'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','zSouth carolina'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','zSouth dakota'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','zTennessee'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','zTexas'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','zVirginia'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','zWest virginia'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB Roll Your Own and Misc','zWisconsin'
INSERT bc_extract_retail_strategy_worktable (mg_name, mgm_name, ml_name) SELECT 'Tobacco and Services','TOB zCigarettes','Default'



UPDATE s
SET default_ranking = dr.default_ranking
FROM bc_extract_retail_strategy_worktable AS s
JOIN (SELECT mg_name, mgm_name, ml_name, 
	ROW_NUMBER() over (partition by mg_name, mgm_name order by mg_name, mgm_name) AS default_ranking
	FROM bc_extract_retail_strategy_worktable
	WHERE ml_name != 'Default') AS dr
ON  s.mg_name = dr.mg_name
AND s.mgm_name = dr.mgm_name
AND s.ml_name = dr.ml_name

INSERT bc_extract_retail_strategy (
	[mg_name],
	[mg_retail_item_type_code],
	[mg_standard_flag],
	[mgm_name],
	[ml_name],
	[ml_default_ranking],
	[ml_high_margin],
	[ml_low_margin],
	[ml_target_margin]
)
SELECT 
	[mg_name],
	'i',
	'n',
	[mgm_name],
	[ml_name],
	[default_ranking],
	[ml_high_margin],
	[ml_low_margin],
	[ml_target_margin]
FROM bc_extract_retail_strategy_worktable

UPDATE bc_extract_retail_strategy
SET mg_standard_flag = 'y'
WHERE mg_name = 'Default Strategy'
AND   mgm_name = 'Default Group'
AND   ml_name = 'Default'

select * from bc_extract_retail_strategy
where mg_standard_flag = 'y'
