IF OBJECT_ID('bcssa_custom_integration.dbo.bc_extract_user_role_mapping') IS NOT NULL
   DROP TABLE bcssa_custom_integration.dbo.bc_extract_user_role_mapping

CREATE TABLE bcssa_custom_integration.dbo.bc_extract_user_role_mapping (
bc_role NVARCHAR(100) NOT NULL,
eso_role NVARCHAR(100) NOT NULL)
GO

INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('Client Admin','Client Admin')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('Inactive','Inactive')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('Speedway Accounting','Accounting Admin')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('Speedway Accounting','Accounting Invoice Reconciliation')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('Speedway Accounting','Accounting Rebate Management')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('Speedway Accounting','Treasury Admin')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('Speedway Admin','Admin')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('Speedway Category Manager','Corporate Read OnlyCategory Management')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('Speedway Credit','Credit')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('Speedway District Manager','District Manager')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('Speedway Downloads','')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('Speedway Environmental','Environmental')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('Speedway Field Auditor','Field Auditor')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('Speedway Field Marketing Coordinator','Corporate Read Only')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('Speedway FIMS','FIMS')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('Speedway Operations Project Manager','Corporate Read Only')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('Speedway Planning & Analysis','Corporate Read Only')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('Speedway Planogram Analyst','Planogram Analyst')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('Speedway Pricebook Analyst','Price Book User')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('Speedway Pricebook Manager','Price Book Management')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('Speedway Region Director','Corporate Read Only')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('Speedway Region Manager','Corporate Read Only')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('Speedway Safety & Security','Loss Prevention')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('Speedway Store Support','Store Support')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('Speedway Store Support Analyst','Store Support Analyst')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('Speedway Store Support Team Lead','Store Support Analyst')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('Speedway Supply Chain Analyst','Corporate Read OnlyMarketing Analytics Analyst')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('Speedway Supply Chain Management','Replenishment User')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('Speedway Supply Chain Manager','Replenishment Management')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('SSA CSR','Store Non-Management')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('SSA CSR2','Store Non-Management')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('SSA Food Steward','Store Non-Management')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('SSA Store Co-Manager','Store Management')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('SSA Store Manager','Store Management')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('Above Store Manager','Above Store Manager')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('BlueCube Admin','ESO Admin')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('BlueCube Admin Support','ESO Admin Support')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('Radiant Client Management','Radiant Client Management')
INSERT bcssa_custom_integration.dbo.bc_extract_user_role_mapping (bc_role, eso_role) VALUES ('Store Manager','Store Manager')
