IF OBJECT_ID('bcssa_custom_integration..bc_extract_rmi_attribute') IS NOT NULL
	DROP TABLE bcssa_custom_integration..bc_extract_rmi_attribute

CREATE TABLE bcssa_custom_integration..bc_extract_rmi_attribute(
	retail_modified_item_id int NOT NULL,
	rmi_name nvarchar(128) NOT NULL,
	attribute1 nvarchar(50) NOT NULL,
	attribute_value1 nvarchar(50) NOT NULL,
	attribute2 nvarchar(50) NULL,
	attribute_value2 nvarchar(50) NULL,
	attribute3 nvarchar(50) NULL,
	attribute_value3 nvarchar(50) NULL,
	attribute4 nvarchar(50) NULL,
	attribute_value4 nvarchar(50) NULL,
	attribute5 nvarchar(50) NULL,
	attribute_value5 nvarchar(50) NULL,
	attribute6 nvarchar(50) NULL,
	attribute_value6 nvarchar(50) NULL,
	attribute7 nvarchar(50) NULL,
	attribute_value7 nvarchar(50) NULL,
	attribute8 nvarchar(50) NULL,
	attribute_value8 nvarchar(50) NULL,
	attribute9 nvarchar(50) NULL,
	attribute_value9 nvarchar(50) NULL,
	attribute10 nvarchar(50) NULL,
	attribute_value10 nvarchar(50) NULL,
	attribute11 nvarchar(50) NULL,
	attribute_value11 nvarchar(50) NULL,
	attribute12 nvarchar(50) NULL,
	attribute_value12 nvarchar(50) NULL,
	attribute13 nvarchar(50) NULL,
	attribute_value13 nvarchar(50) NULL,
	attribute14 nvarchar(50) NULL,
	attribute_value14 nvarchar(50) NULL,
	attribute15 nvarchar(50) NULL,
	attribute_value15 nvarchar(50) NULL,
	attribute16 nvarchar(50) NULL,
	attribute_value16 nvarchar(50) NULL,
	attribute17 nvarchar(50) NULL,
	attribute_value17 nvarchar(50) NULL,
	attribute18 nvarchar(50) NULL,
	attribute_value18 nvarchar(50) NULL,
	attribute19 nvarchar(50) NULL,
	attribute_value19 nvarchar(50) NULL,
	attribute20 nvarchar(50) NULL,
	attribute_value20 nvarchar(50) NULL,
	attribute21 nvarchar(50) NULL,
	attribute_value21 nvarchar(50) NULL,
	attribute22 nvarchar(50) NULL,
	attribute_value22 nvarchar(50) NULL,
	attribute23 nvarchar(50) NULL,
	attribute_value23 nvarchar(50) NULL,
	attribute24 nvarchar(50) NULL,
	attribute_value24 nvarchar(50) NULL,
	attribute25 nvarchar(50) NULL,
	attribute_value25 nvarchar(50) NULL,
	attribute26 nvarchar(50) NULL,
	attribute_value26 nvarchar(50) NULL,
	attribute27 nvarchar(50) NULL,
	attribute_value27 nvarchar(50) NULL,
	attribute28 nvarchar(50) NULL,
	attribute_value28 nvarchar(50) NULL,
	attribute29 nvarchar(50) NULL,
	attribute_value29 nvarchar(50) NULL,
	attribute30 nvarchar(50) NULL,
	attribute_value30 nvarchar(50) NULL
) 

GO


