/****** Run in Custom Integration Database */
DROP TABLE [bc_extract_supplier_merge]
GO
CREATE TABLE [bc_extract_supplier_merge](
	[merge_from_supplier_xref] [nvarchar](50) NOT NULL,
	[merge_to_supplier_xref] [nvarchar](50) NOT NULL
) ON [PRIMARY]

GO

INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_AMRBOTCO','AMRBOTCO'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_AMRIGAS','HRIZNGAS'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_ARCTIC','ARCTIC'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_BARDFLWR','BARDFLWR'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_BERNALC','BERNALC'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_BERNICK','BERNICK'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_BERNINO','BERNINO'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_BEVWHOLE','BEVWHOLE'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_BILLDIST','BILLDIST'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_BLUERHINO','BLUERHINO'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_BREAKTHR','BREAKTHR'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_BROWNSIC','BROWNSIC'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_CANNONTK','CANNONTK'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_CAPITLBV','CAPITLBV'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_CAPPTSMK','CAPPTSMK'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_CLDIST','CLDIST'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_CNTYFAIR','WAUKFAIR'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_COKCHEST','COKCHEST'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_COKGREAT','COKGREAT'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_COKVKING','COKVKING'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_COLLEGE','COLLEGE'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_CRAFTDIS','CRAFTDIS'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_CSTDIST','CSTDIST'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_DAHLHIMR','DAHLHIMR'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_DAKTANEW','DAKTANEW'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_DASDISTR','DASDISTR'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_DDBEVRGE','DDBEVRGE'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_DEANFDNC','DEANFDNC'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_DEBBIE','DEBBIE'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_DUTCHMN','DUTCHMN'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_EARLFOOD','EARLFOOD'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_EASWEEN','EASWEEN'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_EBYSAWIS','EBYSAWIS'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_FISHBAIT','FISHBAIT'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_FRIESSES','FRIESSES'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_FRITO','FRITO'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_GENERAL','GENERAL'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_HBOYDNEL','HBOYDNEL'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_HEGGIES','HEGGIES'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_HIGHDIST','HIGHDIST'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_HOHENSTN','HOHENSTN'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_HOTSTUFF','HOTSTUFF'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_ICEECO','ICEECO'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_INCOMM','INCOMM'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_JHNSNLQ','JHNSNLQ'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_JJTAYMN','JJTAYMN'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_KTCHNFD','KTCHNFD'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_LAKEMAP','LAKEMAP'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_LAKESGAS','LAKESGAS'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_LANGBAIT','LANGBAIT'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_LEEBEVWI','LEEBEVWI'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_LOCHERBR','LOCHERBR'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_LOYALTY','LOYALTY'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_LYNCODIS','LYNCODIS'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_MCDONALD','MCDONALD'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_MCKINNON','MCKINNON'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_MIDAMERI','MIDAMERI'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_MTNCANDY','MTNCANDY'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_NEXXUS','NEXXUS'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_NOVELTY','NOVELTY'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_NRTHWOOD','NRTHWOOD'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_OILDIST','OILDIST'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_PANOGOLD','PANOGOLD'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_PINNACLE','PINNACLE'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_POSTOFFIC','POSTOFFC'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_PRAIRIE','PRAIRIE'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_PRFRMANC','PRFRMANC'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_PUGSINC','PUGSINC'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_REDBULL','REDBULL'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_REINHRDT','REINHART'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_SANDSTRM','SANDSTRM'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_SHAMRCK','SHAMRCK'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_SOLARAY','SOLARAY'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_SRATGALQ','SRATGALQ'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_SUNDANCE','SUNDANCE'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_TOMBSTON','TOMBSTON'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_VIKINGBV','VIKINGBV'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_SMOMCFO','SMOMCFO'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_SMOMFRSH','SMOMFRSH'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_SMOMPKGD','SMOMPKGD'
INSERT bc_extract_supplier_merge (merge_from_supplier_xref, merge_to_supplier_xref) SELECT 'F_SMOMSAND','SMOMSAND'
