-- These commented out inserts are kept for reference.  The rows are from the Speedway BC environment and will be re-created in a nother script w/o red table keys
--INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
--VALUES (1000101, -2147383390, '20', 1000102, 'y', 42, GETDATE())
--INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
--VALUES (1000101, 20857, '600', 1000102, 'n', 42, GETDATE())
--INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
--VALUES (1000101, 20867, '1138840', 1000102, 'n', 42, GETDATE())
--INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
--VALUES (1000101, 20868, '1138839', 1000102, 'n', 42, GETDATE())
--INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
--VALUES (1000101, 20869, '1138842', 1000102, 'n', 42, GETDATE())
--INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
--VALUES (1000101, 20870, '1138841', 1000102, 'n', 42, GETDATE())
--INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
--VALUES (1000101, 20871, '1138843', 1000102, 'n', 42, GETDATE())
--INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
--VALUES (1000101, 20872, '1900', 1000102, 'n', 42, GETDATE())
--INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
--VALUES (1000101, 20875, '5', 1000102, 'y', 42, GETDATE())
--INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
--VALUES (1000101, 500001, '7', 1000102, 'y', 500038, CAST(0x0000A141014E705E AS DateTime))
--INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
--VALUES (1000101, 500002, '23833', 1000102, 'y', 500038, CAST(0x0000A141014EBD3F AS DateTime))
--INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
--VALUES (1000101, 500003, 'C:\Program Files\Radiant\CSSData', 1000102, 'y', 500038, CAST(0x0000A141014EFD80 AS DateTime))

/* Populates the options group based upon the set of options that works with the Speedway POS */
/* There is only one option group for the client. */
DECLARE @ClientID INT
DECLARE @OptionGroupId INT
SELECT @ClientId = MAX(client_id) FROM RAD_SYS_Client
SELECT @OptionGroupId = MAX(pos_option_group_id) FROM POS_Option_Group WHERE client_id = @ClientId

INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 102, '1', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 103, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 104, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 105, '5', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 106, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 107, NULL, @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 108, NULL, @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 109, NULL, @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 110, NULL, @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 111, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 112, 'y', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 118, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 120, '0,0', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 123, '180', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 126, '6', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 129, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 201, '7', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 202, '20', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 203, '21', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 204, 'y', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 205, '04:00', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 206, 'y', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 207, 'y', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 208, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 210, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 211, '1,1134', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 212, '1,1000', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 213, '4', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 214, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 215, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 216, '0,0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 217, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 218, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 219, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 220, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 221, '0', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 222, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 223, '1', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 224, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 225, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 227, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 228, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 229, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 230, '2', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 231, '', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 232, '', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 233, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 234, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 236, '1,1000', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 237, '0,0', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 238, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 239, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 240, '71', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 241, 'y', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 242, '999', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 243, '0', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 244, '', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 245, '1', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 246, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 247, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 248, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 249, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 250, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 251, '', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 252, '', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 253, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 254, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 255, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 256, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 257, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 258, '0', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 259, '', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 260, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 261, '1,1100', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 262, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 263, '1,10003', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 264, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 265, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 266, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 267, '1,10002', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 268, '1', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 269, '', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 270, '0', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 271, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 272, '30', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 274, 'y', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 275, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 276, 'y', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 277, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 278, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 279, 'y', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 280, '9999', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 281, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 282, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 283, 'y', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 284, 'y', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 285, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 286, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 287, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 288, '1', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 289, 'y', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 290, 'y', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 291, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 292, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 293, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 294, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 295, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 296, '10', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 297, '1663860', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 300, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 301, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 302, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 303, 'y', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 304, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 305, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 306, 'y', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 307, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 309, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 310, '0', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 311, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 312, 'y', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 313, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 314, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 315, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 316, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 317, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 322, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 323, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 324, '', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 325, 'y', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 326, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 328, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 330, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 331, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 332, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 333, '-1', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 334, '1,1103', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 335, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 336, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 337, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 338, 'y', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 339, '1,1103', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 340, '123', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 341, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 342, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 343, '0,1', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 344, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 345, 'y', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 346, '300', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 347, 'y', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 348, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 349, 'y', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 350, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 351, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 352, 'y', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 353, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 354, 'y', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 355, '65280', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 356, '52', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 357, 'y', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 358, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 359, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 360, 'y', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 361, '11250603', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 362, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 363, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 364, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 365, '0', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 367, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 368, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 369, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 370, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 371, '1,1000', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 372, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 373, '1,1103', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 374, '0,0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 375, '', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 378, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 379, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 380, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 381, 'y', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 382, '3', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 383, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 384, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 385, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 386, 'y', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 387, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 388, '2', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 390, '', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 391, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 392, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 393, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 394, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 412, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 413, '1', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 414, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 415, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 416, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 417, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 418, '100000', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 419, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 420, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 421, '65535', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 422, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 423, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 424, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 425, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 426, '1,1', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 427, '0,0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 428, '-1', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 429, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 430, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 431, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 432, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 433, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 434, '', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 435, '', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 436, '', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 437, '', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 438, 'y', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 439, 'y', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 440, 'y', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 441, 'y', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 442, 'y', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 443, 'y', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 444, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 445, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 446, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 447, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 448, '', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 449, '', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 450, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 451, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 452, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 453, '30', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 454, '30', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 455, '1,1000', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 456, '', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 457, '', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 458, '1', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 459, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 460, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 461, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 462, '45', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 463, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 464, 'y', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 465, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 466, '-1', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 467, '1', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 468, '5', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 469, '2', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 470, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 471, '', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 472, '1', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 473, '30', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 474, '300', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 475, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 476, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 477, '1,1', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 478, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 479, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 480, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 481, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 482, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 483, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 484, 'y', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 485, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 486, 'y', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 487, 'y', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 488, 'y', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 489, 'y', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 490, '1', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 491, '1', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 500, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 501, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 502, 'y', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 603, '0,0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 604, '1', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 605, '1', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 607, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 608, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 609, '1000', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 610, '60', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 700, 'y', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20624, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20626, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20627, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20628, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20629, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20630, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20631, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20632, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20633, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20634, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20635, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20636, '0', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20637, '1', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20638, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20639, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20640, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20641, '0', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20642, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20643, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20644, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20645, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20646, '0', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20647, '0', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20648, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20649, '0', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20650, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20651, '320', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20652, 'y', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20653, '1', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20654, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20657, 'y', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20658, NULL, @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20659, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20660, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20661, '122000', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20662, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20663, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20664, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20665, '122000', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20666, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20667, '1', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20668, '1033', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20669, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20670, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20671, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20673, '300', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20674, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20676, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20677, '0', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20678, '0', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20679, '0', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20680, '0', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20681, '0', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20682, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20683, '45', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20684, NULL, @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20704, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20712, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20713, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20715, 'y', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20716, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20717, 'y', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20720, '1', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20721, '0', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20722, '0', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20723, '0.0', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20724, '0.0', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20725, '0.0', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20726, '3', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20727, '0.0', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20728, '0.0', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20729, '0', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20730, '30', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20731, '30', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20732, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20733, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20734, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20735, 'y', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20736, 'y', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20737, '1', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20738, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20739, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20740, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20748, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20753, '4294968429', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20769, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20770, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20771, 'y', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20777, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20778, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20779, 'n', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20780, '3', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20781, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20782, 'y', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20783, 'y', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20784, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20786, '3', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20798, '0', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20800, '20', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20803, '99999', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20804, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20805, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20806, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20807, '0', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20808, '0', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20809, '0', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20810, '0', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20811, '0', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20812, '0', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20813, '0', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20815, '0', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20816, '0', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20817, '0', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20818, NULL, @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20819, '0', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20820, 'n', @ClientId, 'y', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20821, 'A', @ClientId, 'n', 42, GETDATE())
INSERT POS_Option_Group_List (pos_option_group_id, pos_option_id, value, client_id, value_editable_flag, last_modified_user_id, last_modified_timestamp)
VALUES (@OptionGroupId, 20822, 'Local Items', @ClientId, 'y', 42, GETDATE())

